### ISSUE TITLE
aerodynamic feedback during reentry

### ISSUE THREAD

**Issue by zERO123331** [Kari1407/Starship-Expansion-Project#76]
i dont know if im just stupid but for me its very hard to keep my starship from turning into a airplane
im playing with rss and everything except the reentry of the ship works awesome
but after some time in reentry, the starship just tilits forwards and so doesnt reduce its horizontal speed as much and basically glides like the spaceshuttle to the ground

this is just feedback from me and if im doin smt wrong please tell me

maybe try giving the front flaps more influence(?)

**Comment by Anomalia2022** [comment]
The front flaps are designed to have minimal influence as they do in real life. You should be sure to keep header tank full and the main body empty, then put more authority limitation on the aft flaps. Starship flies with roll/yaw control on the FWD/AFT and pitch control on the AFT flaps. It will still airplane a bit because KSP jank but you will have much higher control and be able to maintain the 45-65 degree entry angle by allowing more control to the aft flaps.

**Comment by Janus1992** [comment]
Can you provide more details, like a log, a screenshot with all the tanks opened, etc?

**Comment by zERO123331** [comment]
thx ill try that

**Comment by Aria-NL** [comment]
This advice did not work for me; I'm still experiencing uncontrollable pitching forward despite moving all my fuel to the header tank + flap authority tweaks
